### ISSUE TITLE
Emitters not emitting?

### ISSUE THREAD

**Issue by HeroicNate** [MennoMax/gift#5]
First of all this is awesome! I've got it mostly working though I don't really know how the emotes are suppose to work.

The issue I'm having is the signals. I've been searching through the code but can't seem to find if there was some sort of emitter on off code. If I build my own emitters they work, but I can't tap into the ones already in the code. I try connecting to them but they never seem to fire. Any suggestions?

**Comment by MennoMax** [comment]
I'll look into it. Twitch seems to have done some changes to the badge downloading at least, the URL that used to contain channel specific badge info is no longer available.

As long as you set '**get_images**' to true, emotes should be cached in RAM. When also enabling '**disk_cache'**, emotes and badges will also be stored to disk so that you don't have to download them again. Don't forget to specify a cache path as well if you enable the disk cache.

The procedure would then be;

1. Listen to the '**chat_message**' signal
2. Check if the message has emotes in the "emotes" tag in the '**sender_data**'
3. Check if the emote has been downloaded yet ('**get_emote()**' in 'image_cache' will return null if it hasn't)
   - if it hasn't been downloaded yet, remember its id and then wait for the emote_downloaded signal to emit with that id
4. Do whatever you want with the emote

The process is still cumbersome now that I look into it, will probably do some more adjustments. For now, it doesn't work anyway because Twitch seems to have made changes to the API.

Thanks a lot for bringing this to my attention!

**Comment by HeroicNate** [comment]
Ok. I hadn't tried to use the emotes yet but maybe the issue is related to the emitters not firing. 

I was not able to detect the emitters at all for some reason, so listening for "chat_message" would never activate.

**Comment by MennoMax** [comment]
Other signals do work for me. How are your currently using them?

**Comment by HeroicNate** [comment]
At the moment all I'm trying to do it respond to the signal

`func _on_Gift_chat_message(sender_data, message, channel):
	print("chatted")`

or even directly in the script itself:
`func _on_chat_message(sender_data, message, channel):
	print("chatted")`

It never fires, but the function processing the message does activate because I can put all the functionality I want right into it.

**Comment by MennoMax** [comment]
But are you connecting the signal to the function properly?

**Comment by HeroicNate** [comment]
That solved it. 

To create the signal listener I did it in the Node signal menu: 
https://discordapp.com/channels/663542917540872212/663542917540872215/756178926270677092
